.gitignore
controllers/loginController.js
routes/loginRoutes.js
server.js
views/index.ejs
views/login.ejs

"I added a login page accessible from the index page that connects to the profile page. This includes the following:
Added loginRoutes, loginController, and login.ejs.
Updated index.ejs to include an anchor link to the login page.
Created a form in login.ejs that successfully links to the profile page."

I added a login page from the index that connects to the profile.

---

.gitignore
controllers/loginController.js
routes/loginRoutes.js
server.js
views/index.ejs
views/login.ejs
views/profileCreation.ejs

- Added a new EJS template `profileCreation.ejs` for the user profile form.
- Included fields for username, password, passwordRepeat, name, email, timeZone, birthday, and country.
- Fixed duplicate "Email Address" field.
- Corrected input type for country selection.
- Added multiple country options.

Create User Profile Form

---

.gitignore
controllers/loginController.js
routes/loginRoutes.js
server.js
views/index.ejs
views/login.ejs
views/profileCreation.ejs

This pull request establishes the connection between the EJS template, route, controller, and server.js. Key updates include:
Route Definition: Added a new route in server.js to handle incoming requests and direct them to the controller function.
Controller Implementation: The controller processes requests, fetches necessary data, and renders the EJS template.
EJS Template Update: The EJS file is updated to dynamically display data passed from the controller.

Profile Creation ejs connected

---

.gitignore
controllers/loginController.js
controllers/postController.js
routes/loginRoutes.js
routes/postRoutes.js
server.js
views/index.ejs
views/login.ejs
views/profileCreation.ejs

Connected profileCreation.js to profile.js with a put using method override.
added postRoutes.js and postController.js

Added method override 

---

.gitignore
controllers/loginController.js
controllers/postController.js
routes/loginRoutes.js
routes/postRoutes.js
server.js
views/index.ejs
views/login.ejs
views/profile.ejs
views/profileCreation.ejs

"I added a Project creation  page accessible from the profile page. This includes the following:
Added profileRoutes, profileController, and project.ejs.
Updated profile.ejs to include an anchor link to the project page.
Created a form in profile.ejs that successfully links to the project page."

Project creation page linked to the profile page

---

server.js

Just added a public folder and corrected a minor semicolon placement in the server.js file.

Added a public folder

---

.gitignore
README.md
package.json

a really helpful package that would automatically restart the server once any changes have been made, so you guys don't have to keep doing `node server.js` everytime you do some changes or when you encounter any error.
read [this](https://www.geeksforgeeks.org/node-js-nodemon-module/) for more info on how it works

Add package nodemon

---

config/passport.js
controllers/controller.js
controllers/indexController.js
controllers/loginController.js
controllers/postController.js
controllers/profileController.js
controllers/projectController.js
middleware/auth.js
routes/auth.js
routes/google.js
routes/indexRoutes.js
routes/loginRoutes.js
server.js
views/login.ejs
views/partials/header.ejs
views/profile.ejs
views/profileCreation.ejs

so many changes i commit in the code.

Profile redirect can logon in and out of the profile

---

routes/indexRoutes.js

removed a res.render (profile) probably left over from a different test.

This returns a list of the project names to the profile that are associated with the user.

---

controllers/projectController.js
views/profile.ejs
views/project_template.ejs

corrected the link in the profile.ejs
projectController:
added mongoose so the projectList property works properly
corrected the res.render of project_template in getProjects  <<<with a "s"
changed getProject from project/show to project_template.
project_template:
updated to display info about the project. we'll need to store more stuff in the future in this document.

Set up the projectpage to link to the project names in the profile.

---

package-lock.json
package.json
public/css/dragula.css
public/js/dragula.js
public/js/main.js
views/project_template.ejs

add New Drragula npm module you'll need to download this. npm i , i think 
main.js needed a function 
dragula .css and dragula.js were needed.
and the project_template was updated to use these files.

Got dragula working

---

views/project_template.ejs

Users can now create their own boxes for a kanban board. The boxes scale down in size as more are created. The functionality is now there and we can start to implement individual tasks being added and dragged to their appropriate destination.

Update project_template.ejs 

---

public/css/dragula.css
public/css/style.css
public/js/dragula.js
public/js/main.js
views/project_template.ejs

i moved the scrollbar to above the columns. 
i the columns move and the documents move by grabbing the handle bars. '+'
two known errors: the documents can be moved above the title of the Columns.
and the Column doesn't like to move to the first space. <<<< all the way left.

 kanban documents now move

---

views/project_template.ejs

dblclick the column title to edit it.

dblclick the column title to edit it.

---

controllers/profileController.js
routes/profileRoutes.js
views/profile.ejs

Added a delete button next to each project on the profile.ejs (updated profileController, routes, views).

Added the ability to delete individual projects from the profile page

---

controllers/profileController.js
routes/profileRoutes.js
views/editProject.ejs
views/profile.ejs

Added edit and update functionality to the preexisting projects for the logged in user. Created an editProject.ejs file containing a form the send and updates project details. Made notes regarding what different routes do in the profileRouter (it was getting slightly confusing).

added edit button to change the users existing projects 

---

controllers/projectController.js
routes/projectRoutes.js
views/kanban_template.ejs
views/profile.ejs
views/project_template.ejs

project Controller - I added GetKanban; ProjectRoutes - i added Kanban:id;
I created Kanban_template;
profile - i updated to reflect that it doesn't send you directly to the kanban;
project_template was rewritten.

I added the project landing page.

---

views/index.ejs

Looks more sleak and modern. The user scrolls and elements are revealed as they descend the page. Easy implementation with a lot of benefit.

feat: add reveal on scroll animation to index page

---

.gitignore
views/kanban_template.ejs
views/partials/addUserModal.ejs
views/project_template.ejs

Reinstated document dragula functionality and style the addUserModal to match the project-buttons.

Create document form

---

controllers/profileController.js
controllers/projectController.js
public/js/addUserModal.js
public/js/profile.js
routes/projectRoutes.js
views/partials/notifications.ejs

ageNotification pick out the current nottification and notes that it has been read. then gethers the the userId and the whole list of notifications to send back.
addUser modal needed a variable it lost when i removed the js from the ejs.
profile.js now listens to both yes and no buttons, and triggers the 'old' and the notification and removes it from the html, and updates the button's count.
add routing 
notifications.ejs - added a data - id to the  buttons to pass on the notification id.

Finish notifications

---

controllers/profileController.js
package-lock.json
public/css/style.css
public/js/addUserModal.js
public/js/chat.js
public/js/modal.js
public/js/profile.js
routes/profileRoutes.js
server.js
views/partials/addUserModal.ejs
views/partials/notifications.ejs
views/profile.ejs
views/project_template.ejs

[Implement real-time notifications and user management with Socket.IO](https://github.com/jamesAllenJahner3rd/project_manager/commit/83a7dd58d0e46e1827b1c5a16c035f8187f34c8b) 
- Integrated Socket.IO into addUserModal.js, chat.js, modal.js, profile.js, and server.js for real-time communication.
- Enhanced profileRoutes to support Socket.IO and user notifications.
- Added functionality to handle user joining rooms and receiving notifications in profile.js.
- Updated notification rendering in notifications.ejs and profile.ejs to accommodate new real-time features.
- Fixed minor bugs and improved error handling in various scripts.

Socket notifications

---

controllers/profileController.js
public/css/kanban.css
public/js/addUserModal.js
public/js/chat.js
public/js/kanban.js
public/js/modal.js
routes/profileRoutes.js
views/partials/filterDocumentModal.ejs

import the currentProject to addUserModal.js
Update the profile controller to give a user ID or a display name not the entire profile information.
Corrected the display message function in the chat javascript so that it called for the display name and stuff that entire user profile.
The profile route was given a new display name router.
The modal JS had a random variable name that needed to be deleted.

Fix chat username

---

package-lock.json
package.json
public/js/projectTemplate.js
src/projectTemplate.ts
views/partials/tag.ejs
views/project_template.ejs

perColumnPercents() - to parse the data for the Tag chart
refactored the tag chart to type "linear" so dataset would overlay properly
added comments.

Tag figure

---

package.json
public/js/kanban.js
public/js/modal.js
public/js/projectTemplate.js
src/kanban.js
src/kanban.ts
views/partials/filterDocumentModal.ejs

-there was a bug in the filter function Introduced by a lack of the variable list of columns.
-I edited the names of blocked? To actionable so that you could search for blocked documents
-The majority of the rest were formatting.
-package.jason required a type: module

Filter bug
